### ISSUE TITLE
Jak to uzywac

### ISSUE THREAD

**Issue by roblad** [c-soft/satel_integra#1]
Witam,
Mam problem
home assistant -najnowszy 
* Satel Integra version: 

Typ centrali: INTEGRA 64
Wersja: 1.15 z dnia: 2016-03-09
Wersja językowa: 0 (inny język)
Dane zapisane w pamięci FLASH: tak 

* Python version: 3.4 , 2.7 virtualenv
* Operating System: jeese rpi2 

### Description

2017-11-01 11:26:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/home/homeassistant/.homeassistant/deps/lib/python3.4/site-packages/satel_integra/satel_integra.py", line 322, in monitor_status
    yield from self.start_monitoring()
  File "/home/homeassistant/.homeassistant/deps/lib/python3.4/site-packages/satel_integra/satel_integra.py", line 163, in start_monitoring
    resp = yield from self._read_data()
  File "/home/homeassistant/.homeassistant/deps/lib/python3.4/site-packages/satel_integra/satel_integra.py", line 261, in _read_data
    data = yield from self._reader.readuntil(b'\xFE\x0D')
AttributeError: 'StreamReader' object has no attribute 'readuntil'

### What I Did
nic tylko error i nie ziala plugin
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by c-soft** [comment]
Konieczny jest nowszy Python, minimum 3.5.2.

**Comment by roblad** [comment]
Hi,


I have the 3.6.3 currently and it has not been working.
