### ISSUE TITLE
ConnectionResetError: Connection lost 

### ISSUE THREAD

**Issue by djxela** [c-soft/satel_integra#9]
No progres with new component. I have till this same error:
`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/djxela/.homeassistant/deps/lib/python3.6/site-packages/satel_integra/satel_integra.py", line 346, in keep_alive
    yield from self._send_data(data)
  File "/home/djxela/.homeassistant/deps/lib/python3.6/site-packages/satel_integra/satel_integra.py", line 235, in _send_data
    yield from self._writer.drain()
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 333, in drain
    yield from self._protocol._drain_helper()
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 204, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost`

I have new files in two directories:
/home/djxela/.homeassistant/deps/lib/python3.6/site-packages/satel_integra/
and
/CONFIG/homeassistant/components/satel_integra

but traceback is linked with files located in ****/deps/lib/.......

**Comment by c-soft** [comment]
Stack trace shows that you’re still on the old codebase.

**Comment by djxela** [comment]
OK. Component loaded:
You are using a custom component for satel_integra which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Still state is still unknown, but I dont see previous error in log file. 
My logger configuration:
`logger:
  default: warning
  logs:
    homeassistant.components.satel_integra: debug
    satel_integra.satel_integra: debug`)
